name: onebody
homepage: https://church.io/onebody
description:  private member portal for churches, built with Ruby on Rails
changelog: CHANGELOG.md
license: AGPL
dependencies:
  - mysql-server
  - libxml2
  - imagemagick
  - cron
compile_cache_dir: /tmp/pkgr-cache
after_install: build/deb/script/post-install
store_cache: true
