source 'http://rubygems.org'

gem 'rails',                  '~> 3.0.4'
gem 'mysql',                  '~> 2.8.1'
gem 'liquid',                 '~> 2.2.2'
gem 'jquery-rails',           '~> 0.2.4'
gem 'will_paginate',          '~> 3.0.pre2'
gem 'highline',               '~> 1.6.1'
gem 'campaign_monitor_party', '~> 0.2.1'
gem 'whenever',               '~> 0.6.2'
gem 'nokogiri',               '~> 1.4.0'
gem 'builder',                '>= 2.1.2'
gem 'loofah',                 '~> 1.0.0'
gem 'feedzirra',              '~> 0.0.24'
gem 'fastercsv',              '~> 1.5.0'
gem 'pdf-writer',             '~> 1.1.8', :require => 'pdf/writer'
gem 'rubyzip',                '~> 0.9.4', :require => 'zip/zip'
gem 'sanitize',               '~> 1.2.1'
gem 'haml',                   '~> 3.0.24'
gem 'paperclip',              '~> 2.3.6'

group :development, :test do
  gem 'faker',                '~> 0.3.1'
  gem 'shoulda',              '~> 2.11.3'
  gem 'webrat', :git => 'git://github.com/seven1m/webrat.git'
  gem 'selenium-client', :require => 'selenium/client'
  gem 'mongrel'
end
