source 'http://rubygems.org'

gem 'rails', '3.2.13'
gem 'rails_autolink'
gem 'strong_parameters'
gem 'mysql2'
gem 'jquery-rails'
gem 'will_paginate'
gem 'highline'
gem 'whenever'
gem 'nokogiri'
gem 'builder'
gem 'loofah'
gem 'feedzirra'
gem 'rubyzip', require: 'zip/zip'
gem 'sanitize'
gem 'haml'
gem 'sass'
gem 'paperclip'
gem 'exception_notification'
gem 'acts_as_taggable_on_steroids', github: 'PavelNartov/acts_as_taggable_on_steroids', require: 'acts_as_taggable'
gem 'pdf-writer', github: 'metaskills/pdf-writer', require: 'pdf/writer'
gem 'authority'
gem 'load_and_authorize_resource'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'shoulda'
  gem 'pry'
  gem 'zeus'
  gem 'watchr'
end
