-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

CREATE TABLE admins (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `manage_publications` tinyint(1) DEFAULT 0,
  `manage_log` tinyint(1) DEFAULT 0,
  `manage_music` tinyint(1) DEFAULT 0,
  `view_music` tinyint(1) DEFAULT 0,
  `view_hidden_properties` tinyint(1) DEFAULT 0,
  `edit_profiles` tinyint(1) DEFAULT 0,
  `manage_groups` tinyint(1) DEFAULT 0,
  `manage_shares` tinyint(1) DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE attachments (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `message_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `file` blob(10485760) DEFAULT NULL,
  `content_type` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `song_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE comments (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `verse_id` int(11) DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `text` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `event_id` int(11) DEFAULT NULL,
  `recipe_id` int(11) DEFAULT NULL,
  `news_item_id` int(11) DEFAULT NULL,
  `song_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE contacts (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `owner_id` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE events (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `when` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `open` tinyint(1) DEFAULT 0,
  `admins` text DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE events_verses (
  `event_id` int(11) DEFAULT NULL,
  `verse_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE families (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `legacy_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `suffix` varchar(25) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  `home_phone` bigint DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `mail_group` varchar(1) DEFAULT NULL,
  `security_token` varchar(25) DEFAULT NULL,
  `share_address` tinyint(1) DEFAULT 1,
  `share_mobile_phone` tinyint(1) DEFAULT 0,
  `share_work_phone` tinyint(1) DEFAULT 0,
  `share_fax` tinyint(1) DEFAULT 0,
  `share_email` tinyint(1) DEFAULT 0,
  `share_birthday` tinyint(1) DEFAULT 1,
  `share_anniversary` tinyint(1) DEFAULT 1,
  `updated_at` datetime DEFAULT NULL,
  `wall_enabled` tinyint(1) DEFAULT 1,
  `visible` tinyint(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE friendship_requests (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `from_id` int(11) DEFAULT NULL,
  `rejected` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE friendships (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `friend_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `ordering` int(11) DEFAULT 1000
) ENGINE=InnoDB;

CREATE TABLE groups (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `name` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `meets` varchar(100) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `directions` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `private` tinyint(1) DEFAULT 0,
  `address` varchar(255) DEFAULT NULL,
  `members_send` tinyint(1) DEFAULT 1,
  `leader_id` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `hidden` tinyint(1) DEFAULT 0,
  `approved` tinyint(1) DEFAULT 0,
  `link_code` varchar(255) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE log_items (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `model_name` varchar(50) DEFAULT NULL,
  `instance_id` int(11) DEFAULT NULL,
  `changes` text DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `reviewed_on` datetime DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  `flagged_on` datetime DEFAULT NULL,
  `flagged_by` varchar(255) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE memberships (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `group_id` int(11) DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `admin` tinyint(1) DEFAULT 0,
  `get_email` tinyint(1) DEFAULT 1,
  `share_address` tinyint(1) DEFAULT NULL,
  `share_mobile_phone` tinyint(1) DEFAULT NULL,
  `share_work_phone` tinyint(1) DEFAULT NULL,
  `share_fax` tinyint(1) DEFAULT NULL,
  `share_email` tinyint(1) DEFAULT NULL,
  `share_birthday` tinyint(1) DEFAULT NULL,
  `share_anniversary` tinyint(1) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `code` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE messages (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `group_id` int(11) DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `to_person_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `share_email` tinyint(1) DEFAULT 0,
  `wall_id` int(11) DEFAULT NULL,
  `code` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE ministries (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `admin_id` int(11) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE news_items (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `title` varchar(255) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `published` datetime DEFAULT NULL,
  `active` tinyint(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE notes (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `original_url` varchar(255) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE people (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `legacy_id` int(11) DEFAULT NULL,
  `family_id` int(11) DEFAULT NULL,
  `sequence` int(11) DEFAULT NULL,
  `gender` varchar(6) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `suffix` varchar(25) DEFAULT NULL,
  `mobile_phone` bigint DEFAULT NULL,
  `work_phone` bigint DEFAULT NULL,
  `fax` bigint DEFAULT NULL,
  `birthday` datetime DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `email_changed` tinyint(1) DEFAULT 0,
  `website` varchar(255) DEFAULT NULL,
  `classes` varchar(255) DEFAULT NULL,
  `shepherd` varchar(255) DEFAULT NULL,
  `mail_group` varchar(1) DEFAULT NULL,
  `encrypted_password` varchar(100) DEFAULT NULL,
  `service_name` varchar(100) DEFAULT NULL,
  `service_description` text DEFAULT NULL,
  `service_phone` bigint DEFAULT NULL,
  `service_email` varchar(255) DEFAULT NULL,
  `service_website` varchar(255) DEFAULT NULL,
  `activities` text DEFAULT NULL,
  `interests` text DEFAULT NULL,
  `music` text DEFAULT NULL,
  `tv_shows` text DEFAULT NULL,
  `movies` text DEFAULT NULL,
  `books` text DEFAULT NULL,
  `quotes` text DEFAULT NULL,
  `about` text DEFAULT NULL,
  `testimony` text DEFAULT NULL,
  `share_mobile_phone` tinyint(1) DEFAULT NULL,
  `share_work_phone` tinyint(1) DEFAULT NULL,
  `share_fax` tinyint(1) DEFAULT NULL,
  `share_email` tinyint(1) DEFAULT NULL,
  `share_birthday` tinyint(1) DEFAULT NULL,
  `anniversary` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `alternate_email` varchar(255) DEFAULT NULL,
  `email_bounces` int(11) DEFAULT 0,
  `service_category` varchar(100) DEFAULT NULL,
  `get_wall_email` tinyint(1) DEFAULT 1,
  `frozen` tinyint(1) DEFAULT 0,
  `wall_enabled` tinyint(1) DEFAULT NULL,
  `messages_enabled` tinyint(1) DEFAULT 1,
  `service_address` varchar(255) DEFAULT NULL,
  `flags` varchar(255) DEFAULT NULL,
  `music_access` tinyint(1) DEFAULT 0,
  `visible` tinyint(1) DEFAULT 1,
  `parental_consent` varchar(255) DEFAULT NULL,
  `admin_id` int(11) DEFAULT NULL,
  `friends_enabled` tinyint(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE people_verses (
  `person_id` int(11) DEFAULT NULL,
  `verse_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE performances (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `setlist_id` int(11) DEFAULT NULL,
  `song_id` int(11) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE pictures (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `event_id` int(11) DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `cover` tinyint(1) DEFAULT 0,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE prayer_signups (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `start` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `reminded` tinyint(1) DEFAULT 0,
  `other` varchar(100) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE publications (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `file` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE recipes (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `ingredients` text DEFAULT NULL,
  `directions` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `prep` varchar(255) DEFAULT NULL,
  `bake` varchar(255) DEFAULT NULL,
  `serving_size` int(11) DEFAULT NULL,
  `event_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE recipes_tags (
  `tag_id` int(11) DEFAULT NULL,
  `recipe_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE sessions (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `session_id` varchar(255) DEFAULT NULL,
  `data` text DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE setlists (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `start` datetime DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE songs (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `title` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `artists` varchar(500) DEFAULT NULL,
  `album` varchar(255) DEFAULT NULL,
  `image_small_url` varchar(255) DEFAULT NULL,
  `image_medium_url` varchar(255) DEFAULT NULL,
  `image_large_url` varchar(255) DEFAULT NULL,
  `amazon_asin` varchar(50) DEFAULT NULL,
  `amazon_url` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE songs_tags (
  `song_id` int(11) DEFAULT NULL,
  `tag_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE tags (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `name` varchar(50) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE tags_verses (
  `tag_id` int(11) DEFAULT NULL,
  `verse_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE updates (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `person_id` int(11) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `home_phone` bigint DEFAULT NULL,
  `mobile_phone` bigint DEFAULT NULL,
  `work_phone` bigint DEFAULT NULL,
  `fax` bigint DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  `birthday` datetime DEFAULT NULL,
  `anniversary` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `complete` tinyint(1) DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE verifications (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `email` varchar(255) DEFAULT NULL,
  `mobile_phone` bigint DEFAULT NULL,
  `code` int DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE verses (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `reference` varchar(50) DEFAULT NULL,
  `text` text DEFAULT NULL,
  `translation` varchar(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `book` int(11) DEFAULT NULL,
  `chapter` int(11) DEFAULT NULL,
  `verse` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE workers (
  `id` int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  `ministry_id` int(11) DEFAULT NULL,
  `person_id` int(11) DEFAULT NULL,
  `start` datetime DEFAULT NULL,
  `end` datetime DEFAULT NULL,
  `remind_on` datetime DEFAULT NULL,
  `reminded` tinyint(1) DEFAULT 0
) ENGINE=InnoDB;


-- indexes 

CREATE  INDEX `index_sessions_on_session_id` ON sessions (`session_id`);

-- data 


-- schema version meta-info 

CREATE TABLE schema_info (
  `version` int(11) DEFAULT NULL
) ENGINE=InnoDB;

insert into schema_info (version) values (64);
