-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

CREATE TABLE admins (
  "id" serial primary key,
  "manage_publications" boolean DEFAULT 'f',
  "manage_log" boolean DEFAULT 'f',
  "manage_music" boolean DEFAULT 'f',
  "view_music" boolean DEFAULT 'f',
  "view_hidden_properties" boolean DEFAULT 'f',
  "edit_profiles" boolean DEFAULT 'f',
  "manage_groups" boolean DEFAULT 'f',
  "manage_shares" boolean DEFAULT 'f'
);

CREATE TABLE attachments (
  "id" serial primary key,
  "message_id" integer DEFAULT NULL,
  "name" character varying(255) DEFAULT NULL,
  "file" bytea(10485760) DEFAULT NULL,
  "content_type" character varying(50) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "song_id" integer DEFAULT NULL
);

CREATE TABLE comments (
  "id" serial primary key,
  "verse_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "text" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "event_id" integer DEFAULT NULL,
  "recipe_id" integer DEFAULT NULL,
  "news_item_id" integer DEFAULT NULL,
  "song_id" integer DEFAULT NULL
);

CREATE TABLE contacts (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "owner_id" integer DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE events (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "name" character varying(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "when" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "open" boolean DEFAULT 'f',
  "admins" text DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE events_verses (
  "event_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE families (
  "id" serial primary key,
  "legacy_id" integer DEFAULT NULL,
  "name" character varying(255) DEFAULT NULL,
  "last_name" character varying(255) DEFAULT NULL,
  "suffix" character varying(25) DEFAULT NULL,
  "address1" character varying(255) DEFAULT NULL,
  "address2" character varying(255) DEFAULT NULL,
  "city" character varying(255) DEFAULT NULL,
  "state" character varying(2) DEFAULT NULL,
  "zip" character varying(10) DEFAULT NULL,
  "home_phone" bigint DEFAULT NULL,
  "email" character varying(255) DEFAULT NULL,
  "latitude" double DEFAULT NULL,
  "longitude" double DEFAULT NULL,
  "mail_group" character varying(1) DEFAULT NULL,
  "security_token" character varying(25) DEFAULT NULL,
  "share_address" boolean DEFAULT 't',
  "share_mobile_phone" boolean DEFAULT 'f',
  "share_work_phone" boolean DEFAULT 'f',
  "share_fax" boolean DEFAULT 'f',
  "share_email" boolean DEFAULT 'f',
  "share_birthday" boolean DEFAULT 't',
  "share_anniversary" boolean DEFAULT 't',
  "updated_at" timestamp DEFAULT NULL,
  "wall_enabled" boolean DEFAULT 't',
  "visible" boolean DEFAULT 't'
);

CREATE TABLE friendship_requests (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "from_id" integer DEFAULT NULL,
  "rejected" boolean DEFAULT 'f',
  "created_at" timestamp DEFAULT NULL
);

CREATE TABLE friendships (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "friend_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "ordering" integer DEFAULT 1000
);

CREATE TABLE groups (
  "id" serial primary key,
  "name" character varying(100) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "meets" character varying(100) DEFAULT NULL,
  "location" character varying(100) DEFAULT NULL,
  "directions" text DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "category" character varying(50) DEFAULT NULL,
  "creator_id" integer DEFAULT NULL,
  "private" boolean DEFAULT 'f',
  "address" character varying(255) DEFAULT NULL,
  "members_send" boolean DEFAULT 't',
  "leader_id" integer DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "hidden" boolean DEFAULT 'f',
  "approved" boolean DEFAULT 'f',
  "link_code" character varying(255) DEFAULT NULL
);

CREATE TABLE log_items (
  "id" serial primary key,
  "model_name" character varying(50) DEFAULT NULL,
  "instance_id" integer DEFAULT NULL,
  "changes" text DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "reviewed_on" timestamp DEFAULT NULL,
  "reviewed_by" integer DEFAULT NULL,
  "flagged_on" timestamp DEFAULT NULL,
  "flagged_by" character varying(255) DEFAULT NULL
);

CREATE TABLE memberships (
  "id" serial primary key,
  "group_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "admin" boolean DEFAULT 'f',
  "get_email" boolean DEFAULT 't',
  "share_address" boolean DEFAULT NULL,
  "share_mobile_phone" boolean DEFAULT NULL,
  "share_work_phone" boolean DEFAULT NULL,
  "share_fax" boolean DEFAULT NULL,
  "share_email" boolean DEFAULT NULL,
  "share_birthday" boolean DEFAULT NULL,
  "share_anniversary" boolean DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "code" integer DEFAULT NULL
);

CREATE TABLE messages (
  "id" serial primary key,
  "group_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "to_person_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "parent_id" integer DEFAULT NULL,
  "subject" character varying(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "share_email" boolean DEFAULT 'f',
  "wall_id" integer DEFAULT NULL,
  "code" integer DEFAULT NULL
);

CREATE TABLE ministries (
  "id" serial primary key,
  "admin_id" integer DEFAULT NULL,
  "name" character varying(100) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE news_items (
  "id" serial primary key,
  "title" character varying(255) DEFAULT NULL,
  "link" character varying(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "published" timestamp DEFAULT NULL,
  "active" boolean DEFAULT 't'
);

CREATE TABLE notes (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "title" character varying(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "original_url" character varying(255) DEFAULT NULL,
  "deleted" boolean DEFAULT 'f'
);

CREATE TABLE people (
  "id" serial primary key,
  "legacy_id" integer DEFAULT NULL,
  "family_id" integer DEFAULT NULL,
  "sequence" integer DEFAULT NULL,
  "gender" character varying(6) DEFAULT NULL,
  "first_name" character varying(255) DEFAULT NULL,
  "last_name" character varying(255) DEFAULT NULL,
  "suffix" character varying(25) DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "work_phone" bigint DEFAULT NULL,
  "fax" bigint DEFAULT NULL,
  "birthday" timestamp DEFAULT NULL,
  "email" character varying(255) DEFAULT NULL,
  "email_changed" boolean DEFAULT 'f',
  "website" character varying(255) DEFAULT NULL,
  "classes" character varying(255) DEFAULT NULL,
  "shepherd" character varying(255) DEFAULT NULL,
  "mail_group" character varying(1) DEFAULT NULL,
  "encrypted_password" character varying(100) DEFAULT NULL,
  "service_name" character varying(100) DEFAULT NULL,
  "service_description" text DEFAULT NULL,
  "service_phone" bigint DEFAULT NULL,
  "service_email" character varying(255) DEFAULT NULL,
  "service_website" character varying(255) DEFAULT NULL,
  "activities" text DEFAULT NULL,
  "interests" text DEFAULT NULL,
  "music" text DEFAULT NULL,
  "tv_shows" text DEFAULT NULL,
  "movies" text DEFAULT NULL,
  "books" text DEFAULT NULL,
  "quotes" text DEFAULT NULL,
  "about" text DEFAULT NULL,
  "testimony" text DEFAULT NULL,
  "share_mobile_phone" boolean DEFAULT NULL,
  "share_work_phone" boolean DEFAULT NULL,
  "share_fax" boolean DEFAULT NULL,
  "share_email" boolean DEFAULT NULL,
  "share_birthday" boolean DEFAULT NULL,
  "anniversary" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "alternate_email" character varying(255) DEFAULT NULL,
  "email_bounces" integer DEFAULT 0,
  "service_category" character varying(100) DEFAULT NULL,
  "get_wall_email" boolean DEFAULT 't',
  "frozen" boolean DEFAULT 'f',
  "wall_enabled" boolean DEFAULT NULL,
  "messages_enabled" boolean DEFAULT 't',
  "service_address" character varying(255) DEFAULT NULL,
  "flags" character varying(255) DEFAULT NULL,
  "music_access" boolean DEFAULT 'f',
  "visible" boolean DEFAULT 't',
  "parental_consent" character varying(255) DEFAULT NULL,
  "admin_id" integer DEFAULT NULL,
  "friends_enabled" boolean DEFAULT 't'
);

CREATE TABLE people_verses (
  "person_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE performances (
  "id" serial primary key,
  "setlist_id" integer DEFAULT NULL,
  "song_id" integer DEFAULT NULL,
  "ordering" integer DEFAULT NULL
);

CREATE TABLE pictures (
  "id" serial primary key,
  "event_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "cover" boolean DEFAULT 'f',
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE prayer_signups (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "start" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "reminded" boolean DEFAULT 'f',
  "other" character varying(100) DEFAULT NULL
);

CREATE TABLE publications (
  "id" serial primary key,
  "name" character varying(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "file" character varying(255) DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE recipes (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "title" character varying(255) DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "description" text DEFAULT NULL,
  "ingredients" text DEFAULT NULL,
  "directions" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "prep" character varying(255) DEFAULT NULL,
  "bake" character varying(255) DEFAULT NULL,
  "serving_size" integer DEFAULT NULL,
  "event_id" integer DEFAULT NULL
);

CREATE TABLE recipes_tags (
  "tag_id" integer DEFAULT NULL,
  "recipe_id" integer DEFAULT NULL
);

CREATE TABLE sessions (
  "id" serial primary key,
  "session_id" character varying(255) DEFAULT NULL,
  "data" text DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE setlists (
  "id" serial primary key,
  "start" timestamp DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL
);

CREATE TABLE songs (
  "id" serial primary key,
  "title" character varying(255) DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "artists" character varying(500) DEFAULT NULL,
  "album" character varying(255) DEFAULT NULL,
  "image_small_url" character varying(255) DEFAULT NULL,
  "image_medium_url" character varying(255) DEFAULT NULL,
  "image_large_url" character varying(255) DEFAULT NULL,
  "amazon_asin" character varying(50) DEFAULT NULL,
  "amazon_url" character varying(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "person_id" integer DEFAULT NULL
);

CREATE TABLE songs_tags (
  "song_id" integer DEFAULT NULL,
  "tag_id" integer DEFAULT NULL
);

CREATE TABLE tags (
  "id" serial primary key,
  "name" character varying(50) DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE tags_verses (
  "tag_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE updates (
  "id" serial primary key,
  "person_id" integer DEFAULT NULL,
  "first_name" character varying(255) DEFAULT NULL,
  "last_name" character varying(255) DEFAULT NULL,
  "home_phone" bigint DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "work_phone" bigint DEFAULT NULL,
  "fax" bigint DEFAULT NULL,
  "address1" character varying(255) DEFAULT NULL,
  "address2" character varying(255) DEFAULT NULL,
  "city" character varying(255) DEFAULT NULL,
  "state" character varying(2) DEFAULT NULL,
  "zip" character varying(10) DEFAULT NULL,
  "birthday" timestamp DEFAULT NULL,
  "anniversary" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "complete" boolean DEFAULT 'f'
);

CREATE TABLE verifications (
  "id" serial primary key,
  "email" character varying(255) DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "code" int DEFAULT NULL,
  "verified" boolean DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL
);

CREATE TABLE verses (
  "id" serial primary key,
  "reference" character varying(50) DEFAULT NULL,
  "text" text DEFAULT NULL,
  "translation" character varying(10) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "book" integer DEFAULT NULL,
  "chapter" integer DEFAULT NULL,
  "verse" integer DEFAULT NULL
);

CREATE TABLE workers (
  "id" serial primary key,
  "ministry_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "start" timestamp DEFAULT NULL,
  "end" timestamp DEFAULT NULL,
  "remind_on" timestamp DEFAULT NULL,
  "reminded" boolean DEFAULT 'f'
);


-- indexes 

CREATE  INDEX "index_sessions_on_session_id" ON sessions ("session_id");

-- data 


-- schema version meta-info 

CREATE TABLE schema_info (
  "version" integer DEFAULT NULL
);

insert into schema_info (version) values (64);
