-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

CREATE TABLE admins (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "manage_publications" boolean DEFAULT 'f',
  "manage_log" boolean DEFAULT 'f',
  "manage_music" boolean DEFAULT 'f',
  "view_music" boolean DEFAULT 'f',
  "view_hidden_properties" boolean DEFAULT 'f',
  "edit_profiles" boolean DEFAULT 'f',
  "manage_groups" boolean DEFAULT 'f',
  "manage_shares" boolean DEFAULT 'f'
);

CREATE TABLE attachments (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "message_id" integer DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "file" blob(10485760) DEFAULT NULL,
  "content_type" varchar(50) DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "song_id" integer DEFAULT NULL
);

CREATE TABLE comments (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "verse_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "text" text DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "event_id" integer DEFAULT NULL,
  "recipe_id" integer DEFAULT NULL,
  "news_item_id" integer DEFAULT NULL,
  "song_id" integer DEFAULT NULL
);

CREATE TABLE contacts (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "owner_id" integer DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE events (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "when" datetime DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "open" boolean DEFAULT 'f',
  "admins" text DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE events_verses (
  "event_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE families (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "legacy_id" integer DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "last_name" varchar(255) DEFAULT NULL,
  "suffix" varchar(25) DEFAULT NULL,
  "address1" varchar(255) DEFAULT NULL,
  "address2" varchar(255) DEFAULT NULL,
  "city" varchar(255) DEFAULT NULL,
  "state" varchar(2) DEFAULT NULL,
  "zip" varchar(10) DEFAULT NULL,
  "home_phone" bigint DEFAULT NULL,
  "email" varchar(255) DEFAULT NULL,
  "latitude" double DEFAULT NULL,
  "longitude" double DEFAULT NULL,
  "mail_group" varchar(1) DEFAULT NULL,
  "security_token" varchar(25) DEFAULT NULL,
  "share_address" boolean DEFAULT 't',
  "share_mobile_phone" boolean DEFAULT 'f',
  "share_work_phone" boolean DEFAULT 'f',
  "share_fax" boolean DEFAULT 'f',
  "share_email" boolean DEFAULT 'f',
  "share_birthday" boolean DEFAULT 't',
  "share_anniversary" boolean DEFAULT 't',
  "updated_at" datetime DEFAULT NULL,
  "wall_enabled" boolean DEFAULT 't',
  "visible" boolean DEFAULT 't'
);

CREATE TABLE friendship_requests (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "from_id" integer DEFAULT NULL,
  "rejected" boolean DEFAULT 'f',
  "created_at" datetime DEFAULT NULL
);

CREATE TABLE friendships (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "friend_id" integer DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "ordering" integer DEFAULT 1000
);

CREATE TABLE groups (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "name" varchar(100) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "meets" varchar(100) DEFAULT NULL,
  "location" varchar(100) DEFAULT NULL,
  "directions" text DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "category" varchar(50) DEFAULT NULL,
  "creator_id" integer DEFAULT NULL,
  "private" boolean DEFAULT 'f',
  "address" varchar(255) DEFAULT NULL,
  "members_send" boolean DEFAULT 't',
  "leader_id" integer DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "hidden" boolean DEFAULT 'f',
  "approved" boolean DEFAULT 'f',
  "link_code" varchar(255) DEFAULT NULL
);

CREATE TABLE log_items (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "model_name" varchar(50) DEFAULT NULL,
  "instance_id" integer DEFAULT NULL,
  "changes" text DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "reviewed_on" datetime DEFAULT NULL,
  "reviewed_by" integer DEFAULT NULL,
  "flagged_on" datetime DEFAULT NULL,
  "flagged_by" varchar(255) DEFAULT NULL
);

CREATE TABLE memberships (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "group_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "admin" boolean DEFAULT 'f',
  "get_email" boolean DEFAULT 't',
  "share_address" boolean DEFAULT NULL,
  "share_mobile_phone" boolean DEFAULT NULL,
  "share_work_phone" boolean DEFAULT NULL,
  "share_fax" boolean DEFAULT NULL,
  "share_email" boolean DEFAULT NULL,
  "share_birthday" boolean DEFAULT NULL,
  "share_anniversary" boolean DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "code" integer DEFAULT NULL
);

CREATE TABLE messages (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "group_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "to_person_id" integer DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "parent_id" integer DEFAULT NULL,
  "subject" varchar(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "share_email" boolean DEFAULT 'f',
  "wall_id" integer DEFAULT NULL,
  "code" integer DEFAULT NULL
);

CREATE TABLE ministries (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "admin_id" integer DEFAULT NULL,
  "name" varchar(100) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE news_items (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "title" varchar(255) DEFAULT NULL,
  "link" varchar(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "published" datetime DEFAULT NULL,
  "active" boolean DEFAULT 't'
);

CREATE TABLE notes (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "title" varchar(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "original_url" varchar(255) DEFAULT NULL,
  "deleted" boolean DEFAULT 'f'
);

CREATE TABLE people (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "legacy_id" integer DEFAULT NULL,
  "family_id" integer DEFAULT NULL,
  "sequence" integer DEFAULT NULL,
  "gender" varchar(6) DEFAULT NULL,
  "first_name" varchar(255) DEFAULT NULL,
  "last_name" varchar(255) DEFAULT NULL,
  "suffix" varchar(25) DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "work_phone" bigint DEFAULT NULL,
  "fax" bigint DEFAULT NULL,
  "birthday" datetime DEFAULT NULL,
  "email" varchar(255) DEFAULT NULL,
  "email_changed" boolean DEFAULT 'f',
  "website" varchar(255) DEFAULT NULL,
  "classes" varchar(255) DEFAULT NULL,
  "shepherd" varchar(255) DEFAULT NULL,
  "mail_group" varchar(1) DEFAULT NULL,
  "encrypted_password" varchar(100) DEFAULT NULL,
  "service_name" varchar(100) DEFAULT NULL,
  "service_description" text DEFAULT NULL,
  "service_phone" bigint DEFAULT NULL,
  "service_email" varchar(255) DEFAULT NULL,
  "service_website" varchar(255) DEFAULT NULL,
  "activities" text DEFAULT NULL,
  "interests" text DEFAULT NULL,
  "music" text DEFAULT NULL,
  "tv_shows" text DEFAULT NULL,
  "movies" text DEFAULT NULL,
  "books" text DEFAULT NULL,
  "quotes" text DEFAULT NULL,
  "about" text DEFAULT NULL,
  "testimony" text DEFAULT NULL,
  "share_mobile_phone" boolean DEFAULT NULL,
  "share_work_phone" boolean DEFAULT NULL,
  "share_fax" boolean DEFAULT NULL,
  "share_email" boolean DEFAULT NULL,
  "share_birthday" boolean DEFAULT NULL,
  "anniversary" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "alternate_email" varchar(255) DEFAULT NULL,
  "email_bounces" integer DEFAULT 0,
  "service_category" varchar(100) DEFAULT NULL,
  "get_wall_email" boolean DEFAULT 't',
  "frozen" boolean DEFAULT 'f',
  "wall_enabled" boolean DEFAULT NULL,
  "messages_enabled" boolean DEFAULT 't',
  "service_address" varchar(255) DEFAULT NULL,
  "flags" varchar(255) DEFAULT NULL,
  "music_access" boolean DEFAULT 'f',
  "visible" boolean DEFAULT 't',
  "parental_consent" varchar(255) DEFAULT NULL,
  "admin_id" integer DEFAULT NULL,
  "friends_enabled" boolean DEFAULT 't'
);

CREATE TABLE people_verses (
  "person_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE performances (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "setlist_id" integer DEFAULT NULL,
  "song_id" integer DEFAULT NULL,
  "ordering" integer DEFAULT NULL
);

CREATE TABLE pictures (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "event_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "cover" boolean DEFAULT 'f',
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE prayer_signups (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "start" datetime DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "reminded" boolean DEFAULT 'f',
  "other" varchar(100) DEFAULT NULL
);

CREATE TABLE publications (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "file" varchar(255) DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE recipes (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "title" varchar(255) DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "description" text DEFAULT NULL,
  "ingredients" text DEFAULT NULL,
  "directions" text DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "prep" varchar(255) DEFAULT NULL,
  "bake" varchar(255) DEFAULT NULL,
  "serving_size" integer DEFAULT NULL,
  "event_id" integer DEFAULT NULL
);

CREATE TABLE recipes_tags (
  "tag_id" integer DEFAULT NULL,
  "recipe_id" integer DEFAULT NULL
);

CREATE TABLE sessions (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "session_id" varchar(255) DEFAULT NULL,
  "data" text DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE setlists (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "start" datetime DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "created_at" datetime DEFAULT NULL
);

CREATE TABLE songs (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "title" varchar(255) DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "artists" varchar(500) DEFAULT NULL,
  "album" varchar(255) DEFAULT NULL,
  "image_small_url" varchar(255) DEFAULT NULL,
  "image_medium_url" varchar(255) DEFAULT NULL,
  "image_large_url" varchar(255) DEFAULT NULL,
  "amazon_asin" varchar(50) DEFAULT NULL,
  "amazon_url" varchar(255) DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "person_id" integer DEFAULT NULL
);

CREATE TABLE songs_tags (
  "song_id" integer DEFAULT NULL,
  "tag_id" integer DEFAULT NULL
);

CREATE TABLE tags (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "name" varchar(50) DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE tags_verses (
  "tag_id" integer DEFAULT NULL,
  "verse_id" integer DEFAULT NULL
);

CREATE TABLE updates (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "person_id" integer DEFAULT NULL,
  "first_name" varchar(255) DEFAULT NULL,
  "last_name" varchar(255) DEFAULT NULL,
  "home_phone" bigint DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "work_phone" bigint DEFAULT NULL,
  "fax" bigint DEFAULT NULL,
  "address1" varchar(255) DEFAULT NULL,
  "address2" varchar(255) DEFAULT NULL,
  "city" varchar(255) DEFAULT NULL,
  "state" varchar(2) DEFAULT NULL,
  "zip" varchar(10) DEFAULT NULL,
  "birthday" datetime DEFAULT NULL,
  "anniversary" datetime DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "complete" boolean DEFAULT 'f'
);

CREATE TABLE verifications (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "email" varchar(255) DEFAULT NULL,
  "mobile_phone" bigint DEFAULT NULL,
  "code" int DEFAULT NULL,
  "verified" boolean DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL
);

CREATE TABLE verses (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "reference" varchar(50) DEFAULT NULL,
  "text" text DEFAULT NULL,
  "translation" varchar(10) DEFAULT NULL,
  "created_at" datetime DEFAULT NULL,
  "updated_at" datetime DEFAULT NULL,
  "book" integer DEFAULT NULL,
  "chapter" integer DEFAULT NULL,
  "verse" integer DEFAULT NULL
);

CREATE TABLE workers (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "ministry_id" integer DEFAULT NULL,
  "person_id" integer DEFAULT NULL,
  "start" datetime DEFAULT NULL,
  "end" datetime DEFAULT NULL,
  "remind_on" datetime DEFAULT NULL,
  "reminded" boolean DEFAULT 'f'
);


-- indexes 

CREATE  INDEX "index_sessions_on_session_id" ON sessions ("session_id");

-- data 


-- schema version meta-info 

CREATE TABLE schema_info (
  "version" integer DEFAULT NULL
);

insert into schema_info (version) values (64);
