-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

CREATE TABLE admins (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [manage_publications] bit DEFAULT 0,
  [manage_log] bit DEFAULT 0,
  [manage_music] bit DEFAULT 0,
  [view_music] bit DEFAULT 0,
  [view_hidden_properties] bit DEFAULT 0,
  [edit_profiles] bit DEFAULT 0,
  [manage_groups] bit DEFAULT 0,
  [manage_shares] bit DEFAULT 0
);

CREATE TABLE attachments (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [message_id] integer DEFAULT NULL,
  [name] varchar(255) DEFAULT NULL,
  [file] image(10485760) DEFAULT NULL,
  [content_type] varchar(50) DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [song_id] integer DEFAULT NULL
);

CREATE TABLE comments (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [verse_id] integer DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [text] text DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [event_id] integer DEFAULT NULL,
  [recipe_id] integer DEFAULT NULL,
  [news_item_id] integer DEFAULT NULL,
  [song_id] integer DEFAULT NULL
);

CREATE TABLE contacts (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [owner_id] integer DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE events (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [name] varchar(255) DEFAULT NULL,
  [description] text DEFAULT NULL,
  [when] datetime DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [open] bit DEFAULT 0,
  [admins] text DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE events_verses (
  [event_id] integer DEFAULT NULL,
  [verse_id] integer DEFAULT NULL
);

CREATE TABLE families (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [legacy_id] integer DEFAULT NULL,
  [name] varchar(255) DEFAULT NULL,
  [last_name] varchar(255) DEFAULT NULL,
  [suffix] varchar(25) DEFAULT NULL,
  [address1] varchar(255) DEFAULT NULL,
  [address2] varchar(255) DEFAULT NULL,
  [city] varchar(255) DEFAULT NULL,
  [state] varchar(2) DEFAULT NULL,
  [zip] varchar(10) DEFAULT NULL,
  [home_phone] bigint DEFAULT NULL,
  [email] varchar(255) DEFAULT NULL,
  [latitude] double DEFAULT NULL,
  [longitude] double DEFAULT NULL,
  [mail_group] varchar(1) DEFAULT NULL,
  [security_token] varchar(25) DEFAULT NULL,
  [share_address] bit DEFAULT 1,
  [share_mobile_phone] bit DEFAULT 0,
  [share_work_phone] bit DEFAULT 0,
  [share_fax] bit DEFAULT 0,
  [share_email] bit DEFAULT 0,
  [share_birthday] bit DEFAULT 1,
  [share_anniversary] bit DEFAULT 1,
  [updated_at] datetime DEFAULT NULL,
  [wall_enabled] bit DEFAULT 1,
  [visible] bit DEFAULT 1
);

CREATE TABLE friendship_requests (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [from_id] integer DEFAULT NULL,
  [rejected] bit DEFAULT 0,
  [created_at] datetime DEFAULT NULL
);

CREATE TABLE friendships (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [friend_id] integer DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [ordering] integer DEFAULT 1000
);

CREATE TABLE groups (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [name] varchar(100) DEFAULT NULL,
  [description] text DEFAULT NULL,
  [meets] varchar(100) DEFAULT NULL,
  [location] varchar(100) DEFAULT NULL,
  [directions] text DEFAULT NULL,
  [notes] text DEFAULT NULL,
  [category] varchar(50) DEFAULT NULL,
  [creator_id] integer DEFAULT NULL,
  [private] bit DEFAULT 0,
  [address] varchar(255) DEFAULT NULL,
  [members_send] bit DEFAULT 1,
  [leader_id] integer DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [hidden] bit DEFAULT 0,
  [approved] bit DEFAULT 0,
  [link_code] varchar(255) DEFAULT NULL
);

CREATE TABLE log_items (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [model_name] varchar(50) DEFAULT NULL,
  [instance_id] integer DEFAULT NULL,
  [changes] text DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [reviewed_on] datetime DEFAULT NULL,
  [reviewed_by] integer DEFAULT NULL,
  [flagged_on] datetime DEFAULT NULL,
  [flagged_by] varchar(255) DEFAULT NULL
);

CREATE TABLE memberships (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [group_id] integer DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [admin] bit DEFAULT 0,
  [get_email] bit DEFAULT 1,
  [share_address] bit DEFAULT NULL,
  [share_mobile_phone] bit DEFAULT NULL,
  [share_work_phone] bit DEFAULT NULL,
  [share_fax] bit DEFAULT NULL,
  [share_email] bit DEFAULT NULL,
  [share_birthday] bit DEFAULT NULL,
  [share_anniversary] bit DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [code] integer DEFAULT NULL
);

CREATE TABLE messages (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [group_id] integer DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [to_person_id] integer DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [parent_id] integer DEFAULT NULL,
  [subject] varchar(255) DEFAULT NULL,
  [body] text DEFAULT NULL,
  [share_email] bit DEFAULT 0,
  [wall_id] integer DEFAULT NULL,
  [code] integer DEFAULT NULL
);

CREATE TABLE ministries (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [admin_id] integer DEFAULT NULL,
  [name] varchar(100) DEFAULT NULL,
  [description] text DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE news_items (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [title] varchar(255) DEFAULT NULL,
  [link] varchar(255) DEFAULT NULL,
  [body] text DEFAULT NULL,
  [published] datetime DEFAULT NULL,
  [active] bit DEFAULT 1
);

CREATE TABLE notes (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [title] varchar(255) DEFAULT NULL,
  [body] text DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [original_url] varchar(255) DEFAULT NULL,
  [deleted] bit DEFAULT 0
);

CREATE TABLE people (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [legacy_id] integer DEFAULT NULL,
  [family_id] integer DEFAULT NULL,
  [sequence] integer DEFAULT NULL,
  [gender] varchar(6) DEFAULT NULL,
  [first_name] varchar(255) DEFAULT NULL,
  [last_name] varchar(255) DEFAULT NULL,
  [suffix] varchar(25) DEFAULT NULL,
  [mobile_phone] bigint DEFAULT NULL,
  [work_phone] bigint DEFAULT NULL,
  [fax] bigint DEFAULT NULL,
  [birthday] datetime DEFAULT NULL,
  [email] varchar(255) DEFAULT NULL,
  [email_changed] bit DEFAULT 0,
  [website] varchar(255) DEFAULT NULL,
  [classes] varchar(255) DEFAULT NULL,
  [shepherd] varchar(255) DEFAULT NULL,
  [mail_group] varchar(1) DEFAULT NULL,
  [encrypted_password] varchar(100) DEFAULT NULL,
  [service_name] varchar(100) DEFAULT NULL,
  [service_description] text DEFAULT NULL,
  [service_phone] bigint DEFAULT NULL,
  [service_email] varchar(255) DEFAULT NULL,
  [service_website] varchar(255) DEFAULT NULL,
  [activities] text DEFAULT NULL,
  [interests] text DEFAULT NULL,
  [music] text DEFAULT NULL,
  [tv_shows] text DEFAULT NULL,
  [movies] text DEFAULT NULL,
  [books] text DEFAULT NULL,
  [quotes] text DEFAULT NULL,
  [about] text DEFAULT NULL,
  [testimony] text DEFAULT NULL,
  [share_mobile_phone] bit DEFAULT NULL,
  [share_work_phone] bit DEFAULT NULL,
  [share_fax] bit DEFAULT NULL,
  [share_email] bit DEFAULT NULL,
  [share_birthday] bit DEFAULT NULL,
  [anniversary] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [alternate_email] varchar(255) DEFAULT NULL,
  [email_bounces] integer DEFAULT 0,
  [service_category] varchar(100) DEFAULT NULL,
  [get_wall_email] bit DEFAULT 1,
  [frozen] bit DEFAULT 0,
  [wall_enabled] bit DEFAULT NULL,
  [messages_enabled] bit DEFAULT 1,
  [service_address] varchar(255) DEFAULT NULL,
  [flags] varchar(255) DEFAULT NULL,
  [music_access] bit DEFAULT 0,
  [visible] bit DEFAULT 1,
  [parental_consent] varchar(255) DEFAULT NULL,
  [admin_id] integer DEFAULT NULL,
  [friends_enabled] bit DEFAULT 1
);

CREATE TABLE people_verses (
  [person_id] integer DEFAULT NULL,
  [verse_id] integer DEFAULT NULL
);

CREATE TABLE performances (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [setlist_id] integer DEFAULT NULL,
  [song_id] integer DEFAULT NULL,
  [ordering] integer DEFAULT NULL
);

CREATE TABLE pictures (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [event_id] integer DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [cover] bit DEFAULT 0,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE prayer_signups (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [start] datetime DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [reminded] bit DEFAULT 0,
  [other] varchar(100) DEFAULT NULL
);

CREATE TABLE publications (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [name] varchar(255) DEFAULT NULL,
  [description] text DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [file] varchar(255) DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE recipes (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [title] varchar(255) DEFAULT NULL,
  [notes] text DEFAULT NULL,
  [description] text DEFAULT NULL,
  [ingredients] text DEFAULT NULL,
  [directions] text DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [prep] varchar(255) DEFAULT NULL,
  [bake] varchar(255) DEFAULT NULL,
  [serving_size] integer DEFAULT NULL,
  [event_id] integer DEFAULT NULL
);

CREATE TABLE recipes_tags (
  [tag_id] integer DEFAULT NULL,
  [recipe_id] integer DEFAULT NULL
);

CREATE TABLE sessions (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [session_id] varchar(255) DEFAULT NULL,
  [data] text DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE setlists (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [start] datetime DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [created_at] datetime DEFAULT NULL
);

CREATE TABLE songs (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [title] varchar(255) DEFAULT NULL,
  [notes] text DEFAULT NULL,
  [artists] varchar(500) DEFAULT NULL,
  [album] varchar(255) DEFAULT NULL,
  [image_small_url] varchar(255) DEFAULT NULL,
  [image_medium_url] varchar(255) DEFAULT NULL,
  [image_large_url] varchar(255) DEFAULT NULL,
  [amazon_asin] varchar(50) DEFAULT NULL,
  [amazon_url] varchar(255) DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [person_id] integer DEFAULT NULL
);

CREATE TABLE songs_tags (
  [song_id] integer DEFAULT NULL,
  [tag_id] integer DEFAULT NULL
);

CREATE TABLE tags (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [name] varchar(50) DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE tags_verses (
  [tag_id] integer DEFAULT NULL,
  [verse_id] integer DEFAULT NULL
);

CREATE TABLE updates (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [person_id] integer DEFAULT NULL,
  [first_name] varchar(255) DEFAULT NULL,
  [last_name] varchar(255) DEFAULT NULL,
  [home_phone] bigint DEFAULT NULL,
  [mobile_phone] bigint DEFAULT NULL,
  [work_phone] bigint DEFAULT NULL,
  [fax] bigint DEFAULT NULL,
  [address1] varchar(255) DEFAULT NULL,
  [address2] varchar(255) DEFAULT NULL,
  [city] varchar(255) DEFAULT NULL,
  [state] varchar(2) DEFAULT NULL,
  [zip] varchar(10) DEFAULT NULL,
  [birthday] datetime DEFAULT NULL,
  [anniversary] datetime DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [complete] bit DEFAULT 0
);

CREATE TABLE verifications (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [email] varchar(255) DEFAULT NULL,
  [mobile_phone] bigint DEFAULT NULL,
  [code] int DEFAULT NULL,
  [verified] bit DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL
);

CREATE TABLE verses (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [reference] varchar(50) DEFAULT NULL,
  [text] text DEFAULT NULL,
  [translation] varchar(10) DEFAULT NULL,
  [created_at] datetime DEFAULT NULL,
  [updated_at] datetime DEFAULT NULL,
  [book] integer DEFAULT NULL,
  [chapter] integer DEFAULT NULL,
  [verse] integer DEFAULT NULL
);

CREATE TABLE workers (
  [id] int NOT NULL IDENTITY(1,
  1) PRIMARY KEY,
  [ministry_id] integer DEFAULT NULL,
  [person_id] integer DEFAULT NULL,
  [start] datetime DEFAULT NULL,
  [end] datetime DEFAULT NULL,
  [remind_on] datetime DEFAULT NULL,
  [reminded] bit DEFAULT 0
);


-- indexes 

CREATE  INDEX [index_sessions_on_session_id] ON sessions ([session_id]);

-- data 


-- schema version meta-info 

CREATE TABLE schema_info (
  [version] integer DEFAULT NULL
);

insert into schema_info (version) values (64);
