#!/usr/bin/env ruby

# example:
# script/inbox localhost username password

# multisite example:
# script/inbox -s "Site 1" localhost username password

require 'optparse'
options = {}
parser = OptionParser.new do |opts|
  connectors = Dir[File.join(File.dirname(__FILE__), '../lib/connectors/*.rb')].to_a.map { |f| File.split(f).last.split('.').first }.select { |c| !%w(base test example).include? c }
  opts.banner = "Usage: script/inbox [options] host username password"
  opts.on("-s", '--site "Site Name"', "specify site name (if multisite enabled)") do |val|
    options[:site] = val
  end
  opts.on("-e", '--environment production', "specify environment (development, production)") do |val|
    options[:environment] = val
  end
end
parser.parse!

host, username, password = ARGV

if not (host and username and password)
  puts parser.help
  exit
end

RAILS_ENV = options[:environment]

require 'net/pop'
require File.dirname(__FILE__) + '/../config/environment'

logger = RAILS_DEFAULT_LOGGER

logger.info "Running Mail Importer..."

if Setting.get(:features, :multisite)
  Site.current = Site.find_by_name(options[:site])
else
  Site.current = Site.find(1)
end

Net::POP3.start(host, nil, username, password) do |pop|
  if pop.mails.empty?
    logger.info "NO MAIL" 
  else
    pop.mails.each do |email|
      begin
        logger.info "receiving mail..." 
        Notifier.receive(email.pop)
        email.delete
      rescue Exception => e
        logger.error "Error receiving email at " + Time.now.to_s + "::: " + e.message
      end
    end
  end
end
logger.info "Finished Mail Importer." 
