#!/usr/bin/env ruby

require './config/environment'

gemfile = File.read('Gemfile').split(/\n/)

class String
  def inspect
    "'#{to_s}'"
  end
end

class Hash
  def inspect
    map { |k, v| "#{k}: #{v.inspect}" }.join(', ')
  end
end

def gem(*args)
  args
end

Bundler.environment.specs.to_hash.each do |name, (spec)|
  puts name
  if index = gemfile.find_index { |g| g =~ /\Agem '#{name}'/ }
    line = gemfile[index]
    puts line
    args = eval(line)
    if (ref = spec.git_version)
      if args.last.is_a?(Hash)
        args.last[:ref] = ref.strip
      else
        args << { ref: ref.strip }
      end
    else
      version = "~> #{spec.version.to_s}"
      if args[1].is_a?(String)
        args[1] = version
      else
        args.insert(1, version)
      end
    end
    line = "gem #{args.map(&:inspect).join(', ')}"
    puts line
    gemfile[index] = line
  else
    puts 'not found'
  end
  puts
end

File.open('Gemfile', 'w') do |file|
  file.write(gemfile.join("\n") + "\n")
end
