#!/usr/bin/env ruby

RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
require File.join(RAILS_ROOT, 'vendor/daemon')

links_filename = File.join(RAILS_ROOT, 'config/initializers/links.rb')
load links_filename if File.exists?(links_filename)

require 'time'

class Scheduler < Daemon::Base
  TASKS_DIR = defined?(DB_TASKS_PATH) ? DB_TASKS_PATH : File.join(RAILS_ROOT, 'db/tasks')
  DELAY = 15
  MINUTE = 60
  HOUR = 60 * MINUTE
  DAY = 24 * HOUR
  NIGHT_HOURS = 0..3
  
  def self.start
    puts "Scheduler started at #{timestamp}"
    puts
    @rails_root = File.expand_path(RAILS_ROOT)
    @rails_env = ARGV[1] || 'production'
    loop do
      self.run
      sleep DELAY
    end
  end
  
  def self.run
    now = Time.now
    self.run_tasks_and_delete('now')
    if @last_minutely_run.nil? or now >= @last_minutely_run + MINUTE
      self.run_tasks('minutely')
      @last_minutely_run = now
    end
    if @last_hourly_run.nil? or now >= @last_hourly_run + HOUR
      self.run_tasks('hourly') 
      @last_hourly_run = now
    end
    if NIGHT_HOURS.include?(now.hour) and (@last_nightly_run.nil? or now >= @last_nightly_run + DAY)
      self.run_tasks('nightly')
      @last_nightly_run = now
    end
  end
  
  def self.run_task(file, type=nil)
    File.read(file).split(/\r?\n/).each do |line|
      if line.strip.any? and line.strip !~ /^#/
        cmd_line = line.gsub(/RAILS_ROOT/, @rails_root).gsub(/RAILS_ENV/, @rails_env)
        puts (type ? type.capitalize + ' ' : '') + "Task: #{cmd_line}"
        puts "Running at #{timestamp}..."
        #success = system(cmd_line)
        cmd = IO.popen(cmd_line, "w+"); cmd.close_write
        result = cmd.read
        puts "Finished at #{timestamp}"
        puts 'Output:'
        puts result.to_s.strip.any? ? result : '(blank)'
        puts
        STDOUT.flush
      end
    end
  end
  
  def self.timestamp
    Time.now.strftime('%m/%d/%Y %I:%M:%S %p')
  end

  def self.run_tasks(directory)
    Dir[File.join(TASKS_DIR, directory, '*')].each do |file|
      run_task(file, directory) unless file =~ /^\./ or file =~ /\.example$/
    end
  end
  
  def self.run_tasks_and_delete(directory)
    run_tasks(directory).each { |f| File.delete f }
  end
  
  def self.stop
    puts "Scheduler stopped at #{timestamp}"
    puts
  end
end

Scheduler.daemonize(RAILS_ROOT, File.join(RAILS_ROOT, 'log/scheduler.log'))
