#!/usr/bin/env ruby

# example:
# script/worker -e production host username password database

PID_PATH = File.dirname(__FILE__) + '/../tmp/pids/worker.pid'
MAX_PID_LIFE = 30 * 60 # 30 mins

require 'time'
if File.exist?(PID_PATH)
  if Time.now - File.stat(PID_PATH).mtime > MAX_PID_LIFE
    Process.kill('KILL', File.read(PID_PATH).strip.to_i) rescue nil
    File.delete(PID_PATH)
  else
    exit
  end
end

File.open(PID_PATH, 'w') { |f| f.write(Process.pid.to_s) }

require 'optparse'
options = {}
parser = OptionParser.new do |opts|
  opts.banner = "Usage: script/worker -e environment host username password database"
  opts.on("-e", '--environment production', "specify environment (development, production)") do |val|
    options[:environment] = val
  end
  opts.on("--debug") do
    options[:debug] = true
  end
end
parser.parse!

host, username, password, db_name = ARGV

if not (host and username and password and db_name)
  puts parser.help
  File.delete(PID_PATH)
  exit
end

ENV["RAILS_ENV"] = options[:environment]

require 'rubygems'
require 'mysql2'

db = Mysql2::Client.new(host: host, username: username, password: password, database: db_name)
results = db.query("select site_id, id, command from jobs order by created_at")

puts "#{results.count} job(s)" if options[:debug]

if results.count > 0
  require File.expand_path('../../config/environment', __FILE__)
  results.each(as: :array) do |site_id, id, command|
    p [site_id, id, command] if options[:debug]
    logger = Rails.logger
    logger.info "Worker running job #{id} in site #{site_id}..."
    begin
      Site.current = Site.find(site_id)
      logger.info eval(command.gsub(/JOB_ID/, id.to_s))
      puts 'done' if options[:debug]
    rescue => e
      logger.error(e.message)
      backtrace = e.backtrace.is_a?(Array) ? e.backtrace.join("\n") : e.backtrace.to_s
      logger.error(backtrace)
      Notifier.simple_message(Setting.get(:contact, :bug_notification_email), '[OneBody] Worker Error', e.message + "\n\n" + backtrace).deliver
      puts e.message if options[:debug]
    ensure
      db.query("delete from jobs where id = %d" % id)
    end
    logger.info "Finished job #{id}."
  end
elsif options[:debug]
  puts 'No jobs to process.'
end

db.close

File.delete(PID_PATH)
