DB_PHOTO_PATH = "<%= shared_path + '/db/photos' %>"
DB_PUBLICATIONS_PATH = "<%= shared_path + '/db/publications' %>"
DB_ATTACHMENTS_PATH = "<%= shared_path + '/db/attachments' %>"
DB_TASKS_PATH = "<%= shared_path + '/db/tasks' %>"
DEPLOY_THEME_DIR = "<%= shared_path + '/themes' %>"
