DB_PHOTO_PATH        = "<%= shared_path + '/db/photos' %>"
DB_PUBLICATIONS_PATH = "<%= shared_path + '/db/publications' %>"
DB_ATTACHMENTS_PATH  = "<%= shared_path + '/db/attachments' %>"
DB_TASK_FILES_PATH   = "<%= shared_path + '/db/task_files' %>"
DEPLOY_THEME_DIR     = "<%= shared_path + '/themes' %>"
